### PR TITLE
fix(common): set values for select and textarea

### LINKED ISSUE #27: initialValues does not work with <select>
Reproduction of the issue: https://codesandbox.io/s/felte-select-initialvalues-932ld?file=/App.svelte

### PR DESCRIPTION
**Pull request by umanghome**
Closes #27 

Not sure how/where to add/fix tests.

### CODE REVIEW

File: packages/common/src/utils/domUtils.ts [hunk 1]
```diff
@@ -134,38 +140,43 @@ export function setControlValue(
...
-    el.value = '';
-    return;
+    if (el.type === 'file') {
+      el.files = null;
+      el.value = '';
+      return;
+    }
+    el.value = String(fieldValue || '');
+  } else if (isSelectElement(el) || isTextAreaElement(el)) {
+    el.value = String(fieldValue || '');
```
Comment (pablo-abc) [inline packages/common/src/utils/domUtils.ts:178]: I feel this lines can remain as the original line 168, since the behaviour is the same for all the rest of cases (text input, select input and text area).

File: packages/common/src/utils/domUtils.ts [hunk 2]
```diff
@@ -134,38 +140,43 @@ export function setControlValue(
...
   const fieldValue = value;
-  if (el.type === 'checkbox') {
-    const checkboxesDefaultData = fieldValue;
-    if (
-      typeof checkboxesDefaultData === 'undefined' ||
-      typeof checkboxesDefaultData === 'boolean'
-    ) {
-      el.checked = !!checkboxesDefaultData;
+
+  if (isInputElement(el)) {
```
Comment (pablo-abc) [inline packages/common/src/utils/domUtils.ts:146]: The diff is not so friendly here but at first sight I see you've just moved every check inside of an `if (isInputElement(el))` right? If so this looks perfect.

**Review by pablo-abc — CHANGES_REQUESTED** [review]
Another thing I would like to kindly request is to [add a changeset as documented in the Contributing guidelines](https://github.com/pablo-abc/felte/blob/main/CONTRIBUTING.md#making-a-pull-request) (I'm okay with dealing with the testing part)

File: packages/common/src/utils/domUtils.ts (hunk 2 above)
Comment (umanghome) [reply packages/common/src/utils/domUtils.ts:146]: Yep. You could add a `?w=1` query param to this diff's URL and it would remove the whitespace changes.

File: packages/common/src/utils/domUtils.ts (hunk 1 above)
Comment (umanghome) [reply packages/common/src/utils/domUtils.ts:178]: I get these if I remove the conditions.
image

Which means there has to be type guards somewhere.

Comment (umanghome) [reply packages/common/src/utils/domUtils.ts]: I moved the `<input>` specific part within the type guard. The rest doesn't have a check.

**Review by pablo-abc — APPROVED** [review]
